### ISSUE TITLE
confirm that Hypothesis can annotate on top of .. (these files)

### ISSUE THREAD

**Issue by barryrawn** [CMU-Africa-Energy-Scenario-Analysis/Rwanda-E-Mobility#3]
-[ ] a google drive pdf?
-[ ] a .bib file?

**Comment by DaniellaNgarambe** [comment]
![image](https://user-images.githubusercontent.com/43297498/129194572-4b7dceee-0579-4e56-a330-34b57ad40959.png)
![image](https://user-images.githubusercontent.com/43297498/129194619-f1e067f2-9df7-4f83-9a6f-14dd6ef67095.png)
It works for all of these of files, either a google doc, pdf, and a .bib file. Check out these screenshots!
